#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparisOtomasyonu.Fonksiyonlar
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SiparisOtomasyonu")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_Musteriler(TBL_Musteriler instance);
    partial void UpdateTBL_Musteriler(TBL_Musteriler instance);
    partial void DeleteTBL_Musteriler(TBL_Musteriler instance);
    partial void InsertTBL_Urun(TBL_Urun instance);
    partial void UpdateTBL_Urun(TBL_Urun instance);
    partial void DeleteTBL_Urun(TBL_Urun instance);
    partial void InsertTBL_Yoneticiler(TBL_Yoneticiler instance);
    partial void UpdateTBL_Yoneticiler(TBL_Yoneticiler instance);
    partial void DeleteTBL_Yoneticiler(TBL_Yoneticiler instance);
    partial void InsertTBL_Siparisler(TBL_Siparisler instance);
    partial void UpdateTBL_Siparisler(TBL_Siparisler instance);
    partial void DeleteTBL_Siparisler(TBL_Siparisler instance);
    #endregion
		
		public DatabaseDataContext() : 
				base(global::SiparisOtomasyonu.Properties.Settings.Default.SiparisOtomasyonuConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_Musteriler> TBL_Musterilers
		{
			get
			{
				return this.GetTable<TBL_Musteriler>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Urun> TBL_Uruns
		{
			get
			{
				return this.GetTable<TBL_Urun>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Yoneticiler> TBL_Yoneticilers
		{
			get
			{
				return this.GetTable<TBL_Yoneticiler>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Siparisler> TBL_Siparislers
		{
			get
			{
				return this.GetTable<TBL_Siparisler>();
			}
		}
		
		public System.Data.Linq.Table<VW_Siparisler> VW_Siparislers
		{
			get
			{
				return this.GetTable<VW_Siparisler>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Musteriler")]
	public partial class TBL_Musteriler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _MusteriAdi;
		
		private string _MusteriSoyad;
		
		private string _MusteriTelefon;
		
		private string _MusteriMail;
		
		private string _MusteriKullaniciAdi;
		
		private string _MusteriSifre;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMusteriAdiChanging(string value);
    partial void OnMusteriAdiChanged();
    partial void OnMusteriSoyadChanging(string value);
    partial void OnMusteriSoyadChanged();
    partial void OnMusteriTelefonChanging(string value);
    partial void OnMusteriTelefonChanged();
    partial void OnMusteriMailChanging(string value);
    partial void OnMusteriMailChanged();
    partial void OnMusteriKullaniciAdiChanging(string value);
    partial void OnMusteriKullaniciAdiChanged();
    partial void OnMusteriSifreChanging(string value);
    partial void OnMusteriSifreChanged();
    #endregion
		
		public TBL_Musteriler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriAdi", DbType="NVarChar(50)")]
		public string MusteriAdi
		{
			get
			{
				return this._MusteriAdi;
			}
			set
			{
				if ((this._MusteriAdi != value))
				{
					this.OnMusteriAdiChanging(value);
					this.SendPropertyChanging();
					this._MusteriAdi = value;
					this.SendPropertyChanged("MusteriAdi");
					this.OnMusteriAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriSoyad", DbType="NVarChar(50)")]
		public string MusteriSoyad
		{
			get
			{
				return this._MusteriSoyad;
			}
			set
			{
				if ((this._MusteriSoyad != value))
				{
					this.OnMusteriSoyadChanging(value);
					this.SendPropertyChanging();
					this._MusteriSoyad = value;
					this.SendPropertyChanged("MusteriSoyad");
					this.OnMusteriSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriTelefon", DbType="NVarChar(50)")]
		public string MusteriTelefon
		{
			get
			{
				return this._MusteriTelefon;
			}
			set
			{
				if ((this._MusteriTelefon != value))
				{
					this.OnMusteriTelefonChanging(value);
					this.SendPropertyChanging();
					this._MusteriTelefon = value;
					this.SendPropertyChanged("MusteriTelefon");
					this.OnMusteriTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriMail", DbType="NVarChar(150)")]
		public string MusteriMail
		{
			get
			{
				return this._MusteriMail;
			}
			set
			{
				if ((this._MusteriMail != value))
				{
					this.OnMusteriMailChanging(value);
					this.SendPropertyChanging();
					this._MusteriMail = value;
					this.SendPropertyChanged("MusteriMail");
					this.OnMusteriMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriKullaniciAdi", DbType="NVarChar(50)")]
		public string MusteriKullaniciAdi
		{
			get
			{
				return this._MusteriKullaniciAdi;
			}
			set
			{
				if ((this._MusteriKullaniciAdi != value))
				{
					this.OnMusteriKullaniciAdiChanging(value);
					this.SendPropertyChanging();
					this._MusteriKullaniciAdi = value;
					this.SendPropertyChanged("MusteriKullaniciAdi");
					this.OnMusteriKullaniciAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriSifre", DbType="NVarChar(50)")]
		public string MusteriSifre
		{
			get
			{
				return this._MusteriSifre;
			}
			set
			{
				if ((this._MusteriSifre != value))
				{
					this.OnMusteriSifreChanging(value);
					this.SendPropertyChanging();
					this._MusteriSifre = value;
					this.SendPropertyChanged("MusteriSifre");
					this.OnMusteriSifreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Urun")]
	public partial class TBL_Urun : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _UrunAdi;
		
		private string _StokAdet;
		
		private string _UrunFiyat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUrunAdiChanging(string value);
    partial void OnUrunAdiChanged();
    partial void OnStokAdetChanging(string value);
    partial void OnStokAdetChanged();
    partial void OnUrunFiyatChanging(string value);
    partial void OnUrunFiyatChanged();
    #endregion
		
		public TBL_Urun()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunAdi", DbType="NVarChar(50)")]
		public string UrunAdi
		{
			get
			{
				return this._UrunAdi;
			}
			set
			{
				if ((this._UrunAdi != value))
				{
					this.OnUrunAdiChanging(value);
					this.SendPropertyChanging();
					this._UrunAdi = value;
					this.SendPropertyChanged("UrunAdi");
					this.OnUrunAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokAdet", DbType="NVarChar(50)")]
		public string StokAdet
		{
			get
			{
				return this._StokAdet;
			}
			set
			{
				if ((this._StokAdet != value))
				{
					this.OnStokAdetChanging(value);
					this.SendPropertyChanging();
					this._StokAdet = value;
					this.SendPropertyChanged("StokAdet");
					this.OnStokAdetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunFiyat", DbType="NVarChar(50)")]
		public string UrunFiyat
		{
			get
			{
				return this._UrunFiyat;
			}
			set
			{
				if ((this._UrunFiyat != value))
				{
					this.OnUrunFiyatChanging(value);
					this.SendPropertyChanging();
					this._UrunFiyat = value;
					this.SendPropertyChanged("UrunFiyat");
					this.OnUrunFiyatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Yoneticiler")]
	public partial class TBL_Yoneticiler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _YoneticiKullaniciAdi;
		
		private string _YoneticiSifre;
		
		private string _YoneticiAdi;
		
		private string _YoneticiSoyadi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnYoneticiKullaniciAdiChanging(string value);
    partial void OnYoneticiKullaniciAdiChanged();
    partial void OnYoneticiSifreChanging(string value);
    partial void OnYoneticiSifreChanged();
    partial void OnYoneticiAdiChanging(string value);
    partial void OnYoneticiAdiChanged();
    partial void OnYoneticiSoyadiChanging(string value);
    partial void OnYoneticiSoyadiChanged();
    #endregion
		
		public TBL_Yoneticiler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YoneticiKullaniciAdi", DbType="NVarChar(50)")]
		public string YoneticiKullaniciAdi
		{
			get
			{
				return this._YoneticiKullaniciAdi;
			}
			set
			{
				if ((this._YoneticiKullaniciAdi != value))
				{
					this.OnYoneticiKullaniciAdiChanging(value);
					this.SendPropertyChanging();
					this._YoneticiKullaniciAdi = value;
					this.SendPropertyChanged("YoneticiKullaniciAdi");
					this.OnYoneticiKullaniciAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YoneticiSifre", DbType="NVarChar(50)")]
		public string YoneticiSifre
		{
			get
			{
				return this._YoneticiSifre;
			}
			set
			{
				if ((this._YoneticiSifre != value))
				{
					this.OnYoneticiSifreChanging(value);
					this.SendPropertyChanging();
					this._YoneticiSifre = value;
					this.SendPropertyChanged("YoneticiSifre");
					this.OnYoneticiSifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YoneticiAdi", DbType="NVarChar(50)")]
		public string YoneticiAdi
		{
			get
			{
				return this._YoneticiAdi;
			}
			set
			{
				if ((this._YoneticiAdi != value))
				{
					this.OnYoneticiAdiChanging(value);
					this.SendPropertyChanging();
					this._YoneticiAdi = value;
					this.SendPropertyChanged("YoneticiAdi");
					this.OnYoneticiAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YoneticiSoyadi", DbType="NVarChar(50)")]
		public string YoneticiSoyadi
		{
			get
			{
				return this._YoneticiSoyadi;
			}
			set
			{
				if ((this._YoneticiSoyadi != value))
				{
					this.OnYoneticiSoyadiChanging(value);
					this.SendPropertyChanging();
					this._YoneticiSoyadi = value;
					this.SendPropertyChanged("YoneticiSoyadi");
					this.OnYoneticiSoyadiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Siparisler")]
	public partial class TBL_Siparisler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _MusteriID;
		
		private System.Nullable<int> _UrunID;
		
		private string _OdemeTipi;
		
		private string _Adres;
		
		private string _Il;
		
		private string _Ilce;
		
		private string _ToplamUcret;
		
		private string _Adet;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMusteriIDChanging(System.Nullable<int> value);
    partial void OnMusteriIDChanged();
    partial void OnUrunIDChanging(System.Nullable<int> value);
    partial void OnUrunIDChanged();
    partial void OnOdemeTipiChanging(string value);
    partial void OnOdemeTipiChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OnIlChanging(string value);
    partial void OnIlChanged();
    partial void OnIlceChanging(string value);
    partial void OnIlceChanged();
    partial void OnToplamUcretChanging(string value);
    partial void OnToplamUcretChanged();
    partial void OnAdetChanging(string value);
    partial void OnAdetChanged();
    #endregion
		
		public TBL_Siparisler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriID", DbType="Int")]
		public System.Nullable<int> MusteriID
		{
			get
			{
				return this._MusteriID;
			}
			set
			{
				if ((this._MusteriID != value))
				{
					this.OnMusteriIDChanging(value);
					this.SendPropertyChanging();
					this._MusteriID = value;
					this.SendPropertyChanged("MusteriID");
					this.OnMusteriIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunID", DbType="Int")]
		public System.Nullable<int> UrunID
		{
			get
			{
				return this._UrunID;
			}
			set
			{
				if ((this._UrunID != value))
				{
					this.OnUrunIDChanging(value);
					this.SendPropertyChanging();
					this._UrunID = value;
					this.SendPropertyChanged("UrunID");
					this.OnUrunIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OdemeTipi", DbType="NVarChar(50)")]
		public string OdemeTipi
		{
			get
			{
				return this._OdemeTipi;
			}
			set
			{
				if ((this._OdemeTipi != value))
				{
					this.OnOdemeTipiChanging(value);
					this.SendPropertyChanging();
					this._OdemeTipi = value;
					this.SendPropertyChanged("OdemeTipi");
					this.OnOdemeTipiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Il", DbType="NVarChar(50)")]
		public string Il
		{
			get
			{
				return this._Il;
			}
			set
			{
				if ((this._Il != value))
				{
					this.OnIlChanging(value);
					this.SendPropertyChanging();
					this._Il = value;
					this.SendPropertyChanged("Il");
					this.OnIlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilce", DbType="NVarChar(50)")]
		public string Ilce
		{
			get
			{
				return this._Ilce;
			}
			set
			{
				if ((this._Ilce != value))
				{
					this.OnIlceChanging(value);
					this.SendPropertyChanging();
					this._Ilce = value;
					this.SendPropertyChanged("Ilce");
					this.OnIlceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToplamUcret", DbType="NVarChar(50)")]
		public string ToplamUcret
		{
			get
			{
				return this._ToplamUcret;
			}
			set
			{
				if ((this._ToplamUcret != value))
				{
					this.OnToplamUcretChanging(value);
					this.SendPropertyChanging();
					this._ToplamUcret = value;
					this.SendPropertyChanged("ToplamUcret");
					this.OnToplamUcretChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adet", DbType="NVarChar(50)")]
		public string Adet
		{
			get
			{
				return this._Adet;
			}
			set
			{
				if ((this._Adet != value))
				{
					this.OnAdetChanging(value);
					this.SendPropertyChanging();
					this._Adet = value;
					this.SendPropertyChanged("Adet");
					this.OnAdetChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_Siparisler")]
	public partial class VW_Siparisler
	{
		
		private string _MusteriAdi;
		
		private string _MusteriSoyad;
		
		private string _MusteriTelefon;
		
		private string _MusteriMail;
		
		private string _UrunAdi;
		
		private string _OdemeTipi;
		
		private string _Adres;
		
		private string _Il;
		
		private string _Ilce;
		
		private string _ToplamUcret;
		
		private string _Adet;
		
		public VW_Siparisler()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriAdi", DbType="NVarChar(50)")]
		public string MusteriAdi
		{
			get
			{
				return this._MusteriAdi;
			}
			set
			{
				if ((this._MusteriAdi != value))
				{
					this._MusteriAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriSoyad", DbType="NVarChar(50)")]
		public string MusteriSoyad
		{
			get
			{
				return this._MusteriSoyad;
			}
			set
			{
				if ((this._MusteriSoyad != value))
				{
					this._MusteriSoyad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriTelefon", DbType="NVarChar(50)")]
		public string MusteriTelefon
		{
			get
			{
				return this._MusteriTelefon;
			}
			set
			{
				if ((this._MusteriTelefon != value))
				{
					this._MusteriTelefon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriMail", DbType="NVarChar(150)")]
		public string MusteriMail
		{
			get
			{
				return this._MusteriMail;
			}
			set
			{
				if ((this._MusteriMail != value))
				{
					this._MusteriMail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunAdi", DbType="NVarChar(50)")]
		public string UrunAdi
		{
			get
			{
				return this._UrunAdi;
			}
			set
			{
				if ((this._UrunAdi != value))
				{
					this._UrunAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OdemeTipi", DbType="NVarChar(50)")]
		public string OdemeTipi
		{
			get
			{
				return this._OdemeTipi;
			}
			set
			{
				if ((this._OdemeTipi != value))
				{
					this._OdemeTipi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this._Adres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Il", DbType="NVarChar(50)")]
		public string Il
		{
			get
			{
				return this._Il;
			}
			set
			{
				if ((this._Il != value))
				{
					this._Il = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilce", DbType="NVarChar(50)")]
		public string Ilce
		{
			get
			{
				return this._Ilce;
			}
			set
			{
				if ((this._Ilce != value))
				{
					this._Ilce = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToplamUcret", DbType="NVarChar(50)")]
		public string ToplamUcret
		{
			get
			{
				return this._ToplamUcret;
			}
			set
			{
				if ((this._ToplamUcret != value))
				{
					this._ToplamUcret = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adet", DbType="NVarChar(50)")]
		public string Adet
		{
			get
			{
				return this._Adet;
			}
			set
			{
				if ((this._Adet != value))
				{
					this._Adet = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
